--------------------------------------------------------
--  File created - Tuesday-October-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REFRESH_TOKEN
--------------------------------------------------------

  CREATE TABLE "ORACLE"."REFRESH_TOKEN" 
   (	"TOKEN_ID" NUMBER(10,0), 
	"EXPIRY" TIMESTAMP (6) WITH TIME ZONE, 
	"REFRESH_TOKEN" VARCHAR2(255 CHAR), 
	"USERS_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORACLE.REFRESH_TOKEN
SET DEFINE OFF;
Insert into ORACLE.REFRESH_TOKEN (TOKEN_ID,EXPIRY,REFRESH_TOKEN,USERS_ID) values (152,to_timestamp_tz('10-OCT-23 06.05.01.620287000 AM GMT','DD-MON-RR HH.MI.SSXFF AM TZR'),'e9236d1b-789b-4a8f-9e32-c807f3c3b5ff',2);
--------------------------------------------------------
--  DDL for Index SYS_C008104
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."SYS_C008104" ON "ORACLE"."REFRESH_TOKEN" ("TOKEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REFRESH_TOKEN
--------------------------------------------------------

  ALTER TABLE "ORACLE"."REFRESH_TOKEN" MODIFY ("TOKEN_ID" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."REFRESH_TOKEN" ADD PRIMARY KEY ("TOKEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REFRESH_TOKEN
--------------------------------------------------------

  ALTER TABLE "ORACLE"."REFRESH_TOKEN" ADD CONSTRAINT "FKSA85A9LSG3LDY1NKMVS9O5IUM" FOREIGN KEY ("USERS_ID")
	  REFERENCES "ORACLE"."USERS" ("ID") ENABLE;
